name: e820-bios
summary: A tool to dump BIOS e820 memory map
description: e820-bios calls into legacy BIOS interrupt 0x15 to get e820 memory map information
confinement: strict
grade: stable
assumes: [snapd2.45]
base: core18
adopt-info: e820-bios

architectures:
    - amd64
    - i386

parts:
    e820-bios:
        plugin: make
        source: https://github.com/ColinIanKing/e820-bios.git
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"

        build-packages:
            - gcc
            - make
            - libx86-dev
        stage-packages:
            - libx86-dev

        prime:
            - usr/bin/

apps:
    e820-bios:
        plugs: [hardware-observe, system-observe]
        command: usr/bin/e820-bios
