name: e820-bios
version: 0.00.01
summary: A tool to dump BIOS e820 memory map
description: e820-bios calls into legacy BIOS interrupt 0x15 to get e820 memory map information
confinement: strict
grade: stable

parts:
    e820-bios:
        plugin: make
        source: https://github.com/ColinIanKing/e820-bios.git

        build-packages:
            - gcc
            - make
        stage-packages:
            - libx86-dev

        prime:
            - usr/bin/

apps:
    e820-bios:
        plugs: [hardware-observe, system-observe]
        command: usr/bin/e820-bios
